# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32dd404206c3a336f5176d9f49101f87c55095af5ec3b758c9cace69846c2f495ea7384fb0aeed63c1bd914470681c79f106b251f1e78ecbcec81ff604c7e8d6

test:
  secret_key_base: 9232472c2e3c6ff6cdce6427dd58acaf7324cce477b3880b262cb2c7ea6ac8bf79ba876fdfd1c8aa3b7a34567b55db86cd4d6bf348a3efd27ad33498b08f047a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
